# Generated by Django 6.0 on 2025-12-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_orm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField()),
                ('model', models.CharField()),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDiscount_orm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_orm')),
            ],
        ),
    ]
